version: "3"
services:
  jupyterbook:
    image: jupyterbook
    build:
      context: .
    container_name: jupyterbook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    ports:
      - "8000:8000"
    networks:
      - jupyterbook-network

  nginx:
    image: nginx
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "680:80"
      - "6443:443"
    networks:
      - jupyterbook-network

networks:
  jupyterbook-network:
    driver: bridge
