version: "3"
services:
  jupyterbook-hub:
    image: ghcr.io/aminnez/jupyterbook:latest
    build:
      context: .
    container_name: jupyterbook-hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./data:/home
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - jupyterbook-network

  jupyterbook-nginx:
    image: nginx
    container_name: jupyterbook-nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - jupyterbook-network

networks:
  jupyterbook-network:
    driver: bridge
