version: "3"
services:
  jupyterbook-hub:
    image: jupyterbook-hub
    build:
      context: .
    container_name: jupyterbook-hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    ports:
      - "8000:8000"
    networks:
      - jupyterbook-network

  jupyterbook-nginx:
    image: nginx
    container_name: jupyterbook-nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "680:80"
      - "6443:443"
    networks:
      - jupyterbook-network

networks:
  jupyterbook-network:
    driver: bridge
